require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LayersController do

  # This should return the minimal set of attributes required to create a valid
  # Layer. As you add validations to Layer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "content" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LayersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all layers as @layers" do
      layer = Layer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:layers).should eq([layer])
    end
  end

  describe "GET show" do
    it "assigns the requested layer as @layer" do
      layer = Layer.create! valid_attributes
      get :show, {:id => layer.to_param}, valid_session
      assigns(:layer).should eq(layer)
    end
  end

  describe "GET new" do
    it "assigns a new layer as @layer" do
      get :new, {}, valid_session
      assigns(:layer).should be_a_new(Layer)
    end
  end

  describe "GET edit" do
    it "assigns the requested layer as @layer" do
      layer = Layer.create! valid_attributes
      get :edit, {:id => layer.to_param}, valid_session
      assigns(:layer).should eq(layer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Layer" do
        expect {
          post :create, {:layer => valid_attributes}, valid_session
        }.to change(Layer, :count).by(1)
      end

      it "assigns a newly created layer as @layer" do
        post :create, {:layer => valid_attributes}, valid_session
        assigns(:layer).should be_a(Layer)
        assigns(:layer).should be_persisted
      end

      it "redirects to the created layer" do
        post :create, {:layer => valid_attributes}, valid_session
        response.should redirect_to(Layer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved layer as @layer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Layer.any_instance.stub(:save).and_return(false)
        post :create, {:layer => { "content" => "invalid value" }}, valid_session
        assigns(:layer).should be_a_new(Layer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Layer.any_instance.stub(:save).and_return(false)
        post :create, {:layer => { "content" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested layer" do
        layer = Layer.create! valid_attributes
        # Assuming there are no other layers in the database, this
        # specifies that the Layer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Layer.any_instance.should_receive(:update).with({ "content" => "MyString" })
        put :update, {:id => layer.to_param, :layer => { "content" => "MyString" }}, valid_session
      end

      it "assigns the requested layer as @layer" do
        layer = Layer.create! valid_attributes
        put :update, {:id => layer.to_param, :layer => valid_attributes}, valid_session
        assigns(:layer).should eq(layer)
      end

      it "redirects to the layer" do
        layer = Layer.create! valid_attributes
        put :update, {:id => layer.to_param, :layer => valid_attributes}, valid_session
        response.should redirect_to(layer)
      end
    end

    describe "with invalid params" do
      it "assigns the layer as @layer" do
        layer = Layer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Layer.any_instance.stub(:save).and_return(false)
        put :update, {:id => layer.to_param, :layer => { "content" => "invalid value" }}, valid_session
        assigns(:layer).should eq(layer)
      end

      it "re-renders the 'edit' template" do
        layer = Layer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Layer.any_instance.stub(:save).and_return(false)
        put :update, {:id => layer.to_param, :layer => { "content" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested layer" do
      layer = Layer.create! valid_attributes
      expect {
        delete :destroy, {:id => layer.to_param}, valid_session
      }.to change(Layer, :count).by(-1)
    end

    it "redirects to the layers list" do
      layer = Layer.create! valid_attributes
      delete :destroy, {:id => layer.to_param}, valid_session
      response.should redirect_to(layers_url)
    end
  end

end
