require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LightOptionsController do

  # This should return the minimal set of attributes required to create a valid
  # LightOption. As you add validations to LightOption, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "content" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LightOptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all light_options as @light_options" do
      light_option = LightOption.create! valid_attributes
      get :index, {}, valid_session
      assigns(:light_options).should eq([light_option])
    end
  end

  describe "GET show" do
    it "assigns the requested light_option as @light_option" do
      light_option = LightOption.create! valid_attributes
      get :show, {:id => light_option.to_param}, valid_session
      assigns(:light_option).should eq(light_option)
    end
  end

  describe "GET new" do
    it "assigns a new light_option as @light_option" do
      get :new, {}, valid_session
      assigns(:light_option).should be_a_new(LightOption)
    end
  end

  describe "GET edit" do
    it "assigns the requested light_option as @light_option" do
      light_option = LightOption.create! valid_attributes
      get :edit, {:id => light_option.to_param}, valid_session
      assigns(:light_option).should eq(light_option)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LightOption" do
        expect {
          post :create, {:light_option => valid_attributes}, valid_session
        }.to change(LightOption, :count).by(1)
      end

      it "assigns a newly created light_option as @light_option" do
        post :create, {:light_option => valid_attributes}, valid_session
        assigns(:light_option).should be_a(LightOption)
        assigns(:light_option).should be_persisted
      end

      it "redirects to the created light_option" do
        post :create, {:light_option => valid_attributes}, valid_session
        response.should redirect_to(LightOption.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved light_option as @light_option" do
        # Trigger the behavior that occurs when invalid params are submitted
        LightOption.any_instance.stub(:save).and_return(false)
        post :create, {:light_option => { "content" => "invalid value" }}, valid_session
        assigns(:light_option).should be_a_new(LightOption)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LightOption.any_instance.stub(:save).and_return(false)
        post :create, {:light_option => { "content" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested light_option" do
        light_option = LightOption.create! valid_attributes
        # Assuming there are no other light_options in the database, this
        # specifies that the LightOption created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LightOption.any_instance.should_receive(:update).with({ "content" => "MyString" })
        put :update, {:id => light_option.to_param, :light_option => { "content" => "MyString" }}, valid_session
      end

      it "assigns the requested light_option as @light_option" do
        light_option = LightOption.create! valid_attributes
        put :update, {:id => light_option.to_param, :light_option => valid_attributes}, valid_session
        assigns(:light_option).should eq(light_option)
      end

      it "redirects to the light_option" do
        light_option = LightOption.create! valid_attributes
        put :update, {:id => light_option.to_param, :light_option => valid_attributes}, valid_session
        response.should redirect_to(light_option)
      end
    end

    describe "with invalid params" do
      it "assigns the light_option as @light_option" do
        light_option = LightOption.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LightOption.any_instance.stub(:save).and_return(false)
        put :update, {:id => light_option.to_param, :light_option => { "content" => "invalid value" }}, valid_session
        assigns(:light_option).should eq(light_option)
      end

      it "re-renders the 'edit' template" do
        light_option = LightOption.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LightOption.any_instance.stub(:save).and_return(false)
        put :update, {:id => light_option.to_param, :light_option => { "content" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested light_option" do
      light_option = LightOption.create! valid_attributes
      expect {
        delete :destroy, {:id => light_option.to_param}, valid_session
      }.to change(LightOption, :count).by(-1)
    end

    it "redirects to the light_options list" do
      light_option = LightOption.create! valid_attributes
      delete :destroy, {:id => light_option.to_param}, valid_session
      response.should redirect_to(light_options_url)
    end
  end

end
